kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:14-alpine
    commands:
      - yarn install
      - yarn build
  - name: publish
    image: plugins/docker
    settings:
      username: _json_key
      password:
        from_secret: gcr_key
      registry: gcr.io
      repo: gcr.io/pxlblue/backend
      tags: ["${DRONE_COMMIT}", "latest"]
  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server
      kubernetes_cert:
        from_secret: k8s_cert
    environment:
      K8S_CFGB64:
        from_secret: k8s_config_b64
      GKE_KEY:
        from_secret: k8s_gke_key
    commands:
      - echo $GKE_KEY | base64 -d > service-account.json
      - echo $K8S_CFGB64 | base64 -d > kubeconfig.yaml
      - cat kubeconfig.yaml
      - export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
      - export KUBECONFIG=kubeconfig.yaml
      - kubectl config set-context gke --cluster=gke_pxlblue_us-central1-c_pxl-blue --user=gke_pxlblue_us-central1-c_pxl-blue --namespace=production
      - kubectl config use-context gke
      - kubectl get pods
      - kubectl apply -f kubernetes/deployment.yaml
