kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:14
    environment:
      PXL_FONTSPW:
        from_secret: fontszip_pw
    commands:
      - cd src/images/fonts
      - unzip -P $PXL_FONTSPW fonts.zip
      - cd ../../../
      - yarn install
      - yarn build
      - ls dist/images/fonts
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_key
      registry: ghcr.io
      repo: ghcr.io/pxlblue/backend
      tags: ['${DRONE_COMMIT}', 'latest']
