kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:14
    environment:
      PXL_FONTSPW:
        from_secret: fontszip_pw
    commands:
      - cd src/images/fonts
      - unzip -P $PXL_FONTSPW fonts.zip
      - cd ../../../
      - yarn install
      - yarn build
      - ls dist/images/fonts
  - name: publish
    image: plugins/docker
    settings:
      username: _json_key
      password:
        from_secret: gcr_key
      registry: gcr.io
      repo: gcr.io/pxlblue/backend
      tags: ["${DRONE_COMMIT}", "latest"]