name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Docker Action
        uses: jerray/publish-docker-action@v1.0.3
        with:
          username: ${GITHUB_ACTOR}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: pxlblue/backend/server
          auto_tag: true
          allow_pull_request: false
